<?php

use App\Http\Controllers\Api\V1\Admin\OrganizationController as AdminOrganizationController;
use App\Http\Controllers\Api\V1\Admin\RoleController as AdminRoleController;
use App\Http\Controllers\Api\V1\Admin\UserController as AdminUserController;
use App\Http\Controllers\Api\V1\AIPredictionController;
use App\Http\Controllers\Api\V1\AuditLogController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\BatchDocumentController;
use App\Http\Controllers\Api\V1\BatchSplitController;
use App\Http\Controllers\Api\V1\BoatController;
use App\Http\Controllers\Api\V1\CatchRecordController;
use App\Http\Controllers\Api\V1\ColdChainAlertController;
use App\Http\Controllers\Api\V1\FileAssetController;
use App\Http\Controllers\Api\V1\FirebaseSessionController;
use App\Http\Controllers\Api\V1\FishBatchController;
use App\Http\Controllers\Api\V1\FisherReferenceDataController;
use App\Http\Controllers\Api\V1\FishingTripController;
use App\Http\Controllers\Api\V1\IotDeviceController;
use App\Http\Controllers\Api\V1\NotificationController;
use App\Http\Controllers\Api\V1\PackageLabelController;
use App\Http\Controllers\Api\V1\ProcessingRecordController;
use App\Http\Controllers\Api\V1\ProcessingStepController;
use App\Http\Controllers\Api\V1\ProcessorBatchController;
use App\Http\Controllers\Api\V1\ProcessorReferenceDataController;
use App\Http\Controllers\Api\V1\QualityInspectionController;
use App\Http\Controllers\Api\V1\ReportController;
use App\Http\Controllers\Api\V1\RetailAlertController;
use App\Http\Controllers\Api\V1\RetailInventoryController;
use App\Http\Controllers\Api\V1\RetailReportController;
use App\Http\Controllers\Api\V1\RetailSaleController;
use App\Http\Controllers\Api\V1\SupportIssueController;
use App\Http\Controllers\Api\V1\TransportTripController;
use App\Http\Controllers\Api\V1\VehicleController;
use App\Http\Controllers\Consumer\TraceController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::prefix('auth')->group(function (): void {
        Route::post('login', [AuthController::class, 'login'])->middleware('throttle:login');
        Route::post('forgot-password', [AuthController::class, 'forgotPassword'])->middleware('throttle:5,1');
        Route::post('verify-otp', [AuthController::class, 'verifyOtp'])->middleware('throttle:10,1');
        Route::post('reset-password', [AuthController::class, 'resetPassword'])->middleware('throttle:5,1');
    });
    Route::get('public/trace/{qrToken}', [TraceController::class, 'api'])->middleware('throttle:60,1');

    Route::middleware(['auth:sanctum', 'throttle:authenticated-api'])->group(function (): void {
        Route::get('auth/me', [AuthController::class, 'me']);
        Route::match(['put', 'patch'], 'auth/profile', [AuthController::class, 'updateProfile']);
        Route::post('auth/logout', [AuthController::class, 'logout']);
        Route::post('auth/logout-all', [AuthController::class, 'logoutAll']);
        Route::post('auth/change-password', [AuthController::class, 'changePassword']);
        Route::post('firebase/session', FirebaseSessionController::class);
        Route::post('support/issues', [SupportIssueController::class, 'store']);

        Route::post('files', [FileAssetController::class, 'store']);
        Route::get('files/{file}', [FileAssetController::class, 'show'])->name('files.show');
        Route::delete('files/{file}', [FileAssetController::class, 'destroy']);
        Route::get('notifications', [NotificationController::class, 'index']);
        Route::get('notifications/unread-count', [NotificationController::class, 'unreadCount']);
        Route::post('notifications/{notification}/read', [NotificationController::class, 'read']);
        Route::post('notifications/read-all', [NotificationController::class, 'readAll']);
        Route::get('reports/summary', [ReportController::class, 'summary']);
        Route::get('reports/exports', [ReportController::class, 'exports']);
        Route::post('reports/exports', [ReportController::class, 'storeExport']);
        Route::get('reports/exports/{export}', [ReportController::class, 'showExport']);
        Route::get('reports/{report}', [ReportController::class, 'show']);
        Route::get('reports/{report}/csv', [ReportController::class, 'csv']);
        Route::get('reports/{report}/print', [ReportController::class, 'print']);
        Route::get('audit-logs/export', [AuditLogController::class, 'export']);
        Route::get('audit-logs', [AuditLogController::class, 'index']);
        Route::get('audit-logs/{auditLog}', [AuditLogController::class, 'show']);

        Route::prefix('admin')->group(function (): void {
            Route::get('users', [AdminUserController::class, 'index']);
            Route::post('users', [AdminUserController::class, 'store']);
            Route::get('users/{managedUser}', [AdminUserController::class, 'show']);
            Route::match(['put', 'patch'], 'users/{managedUser}', [AdminUserController::class, 'update']);
            Route::post('users/{managedUser}/activate', [AdminUserController::class, 'activate']);
            Route::post('users/{managedUser}/deactivate', [AdminUserController::class, 'deactivate']);
            Route::post('users/{managedUser}/unlock', [AdminUserController::class, 'unlock']);
            Route::post('users/{managedUser}/revoke-sessions', [AdminUserController::class, 'revokeSessions']);
            Route::post('users/{managedUser}/reset-password', [AdminUserController::class, 'resetPassword']);
            Route::get('organizations', [AdminOrganizationController::class, 'index']);
            Route::post('organizations', [AdminOrganizationController::class, 'store']);
            Route::get('organizations/{organization}', [AdminOrganizationController::class, 'show']);
            Route::match(['put', 'patch'], 'organizations/{organization}', [AdminOrganizationController::class, 'update']);
            Route::post('organizations/{organization}/activate', [AdminOrganizationController::class, 'activate']);
            Route::post('organizations/{organization}/deactivate', [AdminOrganizationController::class, 'deactivate']);
            Route::get('roles', [AdminRoleController::class, 'index']);
            Route::get('roles/{role}', [AdminRoleController::class, 'show']);
        });

        Route::apiResource('boats', BoatController::class)->except('update');
        Route::match(['put', 'patch'], 'boats/{boat}', [BoatController::class, 'update']);
        Route::get('fisher/dashboard', [FishingTripController::class, 'dashboard']);
        Route::get('fisher/reference-data', FisherReferenceDataController::class);
        Route::get('fishing-trips', [FishingTripController::class, 'index']);
        Route::post('fishing-trips', [FishingTripController::class, 'store']);
        Route::get('fishing-trips/{fishingTrip}', [FishingTripController::class, 'show']);
        Route::match(['put', 'patch'], 'fishing-trips/{fishingTrip}', [FishingTripController::class, 'update']);
        Route::post('fishing-trips/{fishingTrip}/start', [FishingTripController::class, 'start']);
        Route::post('fishing-trips/{fishingTrip}/complete', [FishingTripController::class, 'complete']);
        Route::post('fishing-trips/{fishingTrip}/cancel', [FishingTripController::class, 'cancel']);
        Route::get('catches', [CatchRecordController::class, 'index']);
        Route::post('catches', [CatchRecordController::class, 'store']);
        Route::get('catches/{catchRecord}', [CatchRecordController::class, 'show']);
        Route::match(['put', 'patch'], 'catches/{catchRecord}', [CatchRecordController::class, 'update']);
        Route::delete('catches/{catchRecord}', [CatchRecordController::class, 'destroy']);
        Route::get('batches', [FishBatchController::class, 'index']);
        Route::post('batches', [FishBatchController::class, 'store']);
        Route::get('batches/{batch}', [FishBatchController::class, 'show']);
        Route::get('batches/{batch}/qr', [FishBatchController::class, 'qr']);
        Route::get('batches/{batch}/timeline', [FishBatchController::class, 'timeline']);
        Route::get('batches/{batch}/documents', [BatchDocumentController::class, 'index']);
        Route::post('batches/{batch}/documents', [BatchDocumentController::class, 'store']);
        Route::get('batches/{batch}/ai-predictions', [AIPredictionController::class, 'index']);
        Route::get('batches/{batch}/ai-predictions/latest', [AIPredictionController::class, 'latest']);
        Route::post('batches/{batch}/ai-predictions/request', [AIPredictionController::class, 'store']);
        Route::post('batches/{batch}/split', [BatchSplitController::class, 'store']);
        Route::get('batches/{batch}/children', [BatchSplitController::class, 'index']);

        Route::get('processor/dashboard', [ProcessorBatchController::class, 'dashboard']);
        Route::get('processor/reference-data', ProcessorReferenceDataController::class);
        Route::get('processor/incoming-batches', [ProcessorBatchController::class, 'incoming']);
        Route::get('processor/resolve-batch', [ProcessorBatchController::class, 'resolve']);
        Route::get('processor/history', [ProcessorBatchController::class, 'history']);
        Route::get('processor/batches/{batch}', [ProcessorBatchController::class, 'show']);
        Route::post('processor/batches/{batch}/accept', [ProcessorBatchController::class, 'accept']);
        Route::post('processor/batches/{batch}/reject', [ProcessorBatchController::class, 'reject']);
        Route::post('processing-records', [ProcessingRecordController::class, 'store']);
        Route::get('processing-records/{processingRecord}', [ProcessingRecordController::class, 'show']);
        Route::put('processing-records/{processingRecord}', [ProcessingRecordController::class, 'update']);
        Route::post('processing-records/{processingRecord}/steps/{step}/start', [ProcessingStepController::class, 'start']);
        Route::post('processing-records/{processingRecord}/steps/{step}/complete', [ProcessingStepController::class, 'complete']);
        Route::post('quality-inspections', [QualityInspectionController::class, 'store']);
        Route::get('quality-inspections/{inspection}', [QualityInspectionController::class, 'show']);
        Route::get('package-labels/{label}', [PackageLabelController::class, 'show']);
        Route::get('package-labels/{label}/print', [PackageLabelController::class, 'print']);

        Route::get('retail/dashboard', [RetailInventoryController::class, 'dashboard']);
        Route::get('retail/incoming-labels', [RetailInventoryController::class, 'incoming']);
        Route::get('retail/receipts', [RetailInventoryController::class, 'receipts']);
        Route::post('retail/package-labels/{label}/receive', [RetailInventoryController::class, 'receive']);
        Route::get('retail/inventory-lots', [RetailInventoryController::class, 'index']);
        Route::get('retail/inventory-lots/{lot}', [RetailInventoryController::class, 'show']);
        Route::post('retail/inventory-lots/{lot}/reserve', [RetailInventoryController::class, 'reserve']);
        Route::post('retail/inventory-lots/{lot}/release', [RetailInventoryController::class, 'release']);
        Route::post('retail/inventory-lots/{lot}/recall', [RetailInventoryController::class, 'recall']);
        Route::post('retail/inventory-lots/{lot}/expire', [RetailInventoryController::class, 'expire']);
        Route::get('retail/sales', [RetailSaleController::class, 'index']);
        Route::post('retail/sales', [RetailSaleController::class, 'store']);
        Route::get('retail/sales/{sale}', [RetailSaleController::class, 'show']);

        Route::get('retailer/dashboard', [RetailInventoryController::class, 'dashboard']);
        Route::get('retailer/resolve-label', [RetailInventoryController::class, 'resolveLabel']);
        Route::get('retailer/receipts', [RetailInventoryController::class, 'receipts']);
        Route::post('retailer/receipts', [RetailInventoryController::class, 'storeReceipt']);
        Route::get('retailer/receipts/{receipt}', [RetailInventoryController::class, 'receipt']);
        Route::get('retailer/inventory', [RetailInventoryController::class, 'index']);
        Route::get('retailer/inventory/{lot}', [RetailInventoryController::class, 'show']);
        Route::post('retailer/stock-adjustments', [RetailInventoryController::class, 'stockAdjustment']);
        Route::get('retailer/sales', [RetailSaleController::class, 'index']);
        Route::post('retailer/sales', [RetailSaleController::class, 'store']);
        Route::get('retailer/sales/{sale}', [RetailSaleController::class, 'show']);
        Route::get('retailer/alerts', [RetailAlertController::class, 'index']);
        Route::post('retailer/recalls/{alert}/quarantine', [RetailAlertController::class, 'quarantine']);
        Route::post('retailer/alerts/{alert}/resolve', [RetailAlertController::class, 'resolve']);
        Route::get('retailer/reports/summary', [RetailReportController::class, 'summary']);
        Route::get('retailer/reports/sales', [RetailReportController::class, 'sales']);
        Route::get('retailer/reports/inventory', [RetailReportController::class, 'inventory']);

        Route::apiResource('vehicles', VehicleController::class);
        Route::get('transporter/dashboard', [TransportTripController::class, 'dashboard']);
        Route::get('transporter/available-batches', [TransportTripController::class, 'availableBatches']);
        Route::get('transporter/resolve-batch', [TransportTripController::class, 'resolveBatch']);
        Route::get('transport-trips', [TransportTripController::class, 'index']);
        Route::post('transport-trips', [TransportTripController::class, 'store']);
        Route::get('transport-trips/{transportTrip}', [TransportTripController::class, 'show']);
        Route::match(['put', 'patch'], 'transport-trips/{transportTrip}', [TransportTripController::class, 'update']);
        Route::post('transport-trips/{transportTrip}/batches', [TransportTripController::class, 'addBatch']);
        Route::delete('transport-trips/{transportTrip}/batches/{batch}', [TransportTripController::class, 'removeBatch']);
        Route::post('transport-trips/{transportTrip}/device', [TransportTripController::class, 'assignDevice']);
        Route::delete('transport-trips/{transportTrip}/device', [TransportTripController::class, 'removeDevice']);
        Route::get('transport-trips/{transportTrip}/checklist', [TransportTripController::class, 'checklist']);
        Route::post('transport-trips/{transportTrip}/checklist', [TransportTripController::class, 'updateChecklist']);
        Route::post('transport-trips/{transportTrip}/start', [TransportTripController::class, 'start']);
        Route::post('transport-trips/{transportTrip}/arrive', [TransportTripController::class, 'arrive']);
        Route::post('transport-trips/{transportTrip}/complete', [TransportTripController::class, 'complete']);
        Route::post('transport-trips/{transportTrip}/cancel', [TransportTripController::class, 'cancel']);
        Route::post('transport-trips/{transportTrip}/incidents', [TransportTripController::class, 'incident']);
        Route::post('transport-trips/{transportTrip}/delivery-confirmation', [TransportTripController::class, 'confirmDelivery']);
        Route::get('transport-trips/{transportTrip}/live-access', [TransportTripController::class, 'liveAccess']);
        Route::get('transport-trips/{transportTrip}/sensor-readings', [TransportTripController::class, 'readings']);
        Route::get('transport-trips/{transportTrip}/sensor-readings/latest', [TransportTripController::class, 'latest']);
        Route::get('transport-trips/{transportTrip}/sensor-summary', [TransportTripController::class, 'sensorSummary']);
        Route::get('transport-trips/{transportTrip}/alerts', [ColdChainAlertController::class, 'index']);
        Route::post('alerts/{alert}/acknowledge', [ColdChainAlertController::class, 'acknowledge']);

        Route::get('iot/devices', [IotDeviceController::class, 'index']);
        Route::post('iot/devices', [IotDeviceController::class, 'store']);
        Route::get('iot/devices/{device}', [IotDeviceController::class, 'show']);
        Route::match(['put', 'patch'], 'iot/devices/{device}', [IotDeviceController::class, 'update']);
        Route::post('iot/devices/{device}/activate', [IotDeviceController::class, 'activate']);
        Route::post('iot/devices/{device}/deactivate', [IotDeviceController::class, 'deactivate']);
        Route::post('iot/devices/{device}/firebase-provision', [IotDeviceController::class, 'provision']);
        Route::post('iot/devices/{device}/firebase-disable', [IotDeviceController::class, 'disableFirebase']);
        Route::post('iot/devices/{device}/firebase-rotate', [IotDeviceController::class, 'rotate']);
        Route::get('iot/devices/{device}/health', [IotDeviceController::class, 'health']);
        Route::get('iot/devices/{device}/readings', [IotDeviceController::class, 'readings']);
        Route::get('iot/devices/{device}/latest-reading', [IotDeviceController::class, 'latestReading']);
        Route::get('iot/devices/{device}/firebase-sync-status', [IotDeviceController::class, 'syncStatus']);
    });
});
