<?php

use App\Http\Controllers\Admin\AdminProfileController;
use App\Http\Controllers\Admin\AlertRuleController;
use App\Http\Controllers\Admin\AuditLogController;
use App\Http\Controllers\Admin\AuthController as AdminAuthController;
use App\Http\Controllers\Admin\BatchController;
use App\Http\Controllers\Admin\ComplianceOperationsController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\FishingOperationsController;
use App\Http\Controllers\Admin\FishingReferenceDataController;
use App\Http\Controllers\Admin\OrganizationController;
use App\Http\Controllers\Admin\ProcessorOperationsController;
use App\Http\Controllers\Admin\RetailOperationsController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SystemSettingController;
use App\Http\Controllers\Admin\TransportOperationsController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Consumer\TraceController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/admin');
Route::get('/trace/{qrToken}', [TraceController::class, 'show'])->name('trace.show')->middleware('throttle:60,1');
Route::middleware('guest')->group(function (): void {
    Route::get('/admin/login', [AdminAuthController::class, 'create'])->name('admin.login');
    Route::post('/admin/login', [AdminAuthController::class, 'store'])->name('admin.login.store')->middleware('throttle:login');
});
Route::prefix('admin')->middleware('auth')->group(function (): void {
    Route::get('/', DashboardController::class)->name('admin.dashboard');
    Route::get('/audit-logs', AuditLogController::class)->name('admin.audit-logs');
    Route::get('/batches/export', [BatchController::class, 'export'])->name('admin.batches.export');
    Route::get('/batches', [BatchController::class, 'index'])->name('admin.batches.index');
    Route::get('/batches/{batch}/qr', [BatchController::class, 'qr'])->name('admin.batches.qr');
    Route::get('/batches/{batch}', [BatchController::class, 'show'])->name('admin.batches.show');
    Route::prefix('fishing')->group(function (): void {
        Route::get('/fishers', [FishingOperationsController::class, 'fishers'])->name('admin.fishing.fishers.index');
        Route::get('/fishers/{fisher}', [FishingOperationsController::class, 'fisher'])->name('admin.fishing.fishers.show');
        Route::get('/boats', [FishingOperationsController::class, 'boats'])->name('admin.fishing.boats.index');
        Route::get('/boats/{boat}', [FishingOperationsController::class, 'boat'])->name('admin.fishing.boats.show');
        Route::get('/trips/export', [FishingOperationsController::class, 'exportTrips'])->name('admin.fishing.trips.export');
        Route::get('/trips', [FishingOperationsController::class, 'trips'])->name('admin.fishing.trips.index');
        Route::get('/trips/{trip}', [FishingOperationsController::class, 'trip'])->name('admin.fishing.trips.show');
        Route::get('/catches/export', [FishingOperationsController::class, 'exportCatches'])->name('admin.fishing.catches.export');
        Route::get('/catches', [FishingOperationsController::class, 'catches'])->name('admin.fishing.catches.index');
        Route::get('/catches/{catchRecord}/images/{file}', [FishingOperationsController::class, 'catchImage'])->name('admin.fishing.catches.images.show');
        Route::get('/catches/{catchRecord}', [FishingOperationsController::class, 'catch'])->name('admin.fishing.catches.show');
    });
    Route::prefix('reference-data')->group(function (): void {
        Route::get('/species', [FishingReferenceDataController::class, 'species'])->name('admin.reference-data.species.index');
        Route::get('/species/create', [FishingReferenceDataController::class, 'createSpecies'])->name('admin.reference-data.species.create');
        Route::post('/species', [FishingReferenceDataController::class, 'storeSpecies'])->name('admin.reference-data.species.store');
        Route::get('/species/{species}/edit', [FishingReferenceDataController::class, 'editSpecies'])->name('admin.reference-data.species.edit');
        Route::put('/species/{species}', [FishingReferenceDataController::class, 'updateSpecies'])->name('admin.reference-data.species.update');
        Route::get('/gear', [FishingReferenceDataController::class, 'gear'])->name('admin.reference-data.gear.index');
        Route::get('/gear/create', [FishingReferenceDataController::class, 'createGear'])->name('admin.reference-data.gear.create');
        Route::post('/gear', [FishingReferenceDataController::class, 'storeGear'])->name('admin.reference-data.gear.store');
        Route::get('/gear/{gear}/edit', [FishingReferenceDataController::class, 'editGear'])->name('admin.reference-data.gear.edit');
        Route::put('/gear/{gear}', [FishingReferenceDataController::class, 'updateGear'])->name('admin.reference-data.gear.update');
        Route::get('/landing-sites', [FishingReferenceDataController::class, 'sites'])->name('admin.reference-data.sites.index');
        Route::get('/landing-sites/create', [FishingReferenceDataController::class, 'createSite'])->name('admin.reference-data.sites.create');
        Route::post('/landing-sites', [FishingReferenceDataController::class, 'storeSite'])->name('admin.reference-data.sites.store');
        Route::get('/landing-sites/{site}/edit', [FishingReferenceDataController::class, 'editSite'])->name('admin.reference-data.sites.edit');
        Route::put('/landing-sites/{site}', [FishingReferenceDataController::class, 'updateSite'])->name('admin.reference-data.sites.update');
    });
    Route::prefix('transport')->group(function (): void {
        Route::get('/transporters', [TransportOperationsController::class, 'transporters'])->name('admin.transport.transporters.index');
        Route::get('/transporters/{transporter}', [TransportOperationsController::class, 'transporter'])->name('admin.transport.transporters.show');
        Route::get('/vehicles', [TransportOperationsController::class, 'vehicles'])->name('admin.transport.vehicles.index');
        Route::get('/vehicles/{vehicle}', [TransportOperationsController::class, 'vehicle'])->name('admin.transport.vehicles.show');
        Route::get('/trips', [TransportOperationsController::class, 'trips'])->name('admin.transport.trips.index');
        Route::get('/trips/{trip}', [TransportOperationsController::class, 'trip'])->name('admin.transport.trips.show');
        Route::get('/devices', [TransportOperationsController::class, 'devices'])->name('admin.transport.devices.index');
        Route::get('/devices/create', [TransportOperationsController::class, 'createDevice'])->name('admin.transport.devices.create');
        Route::post('/devices', [TransportOperationsController::class, 'storeDevice'])->name('admin.transport.devices.store');
        Route::post('/devices/{device}/provision', [TransportOperationsController::class, 'provisionDevice'])->name('admin.transport.devices.provision');
        Route::get('/devices/{device}', [TransportOperationsController::class, 'device'])->name('admin.transport.devices.show');
        Route::get('/telemetry/export', [TransportOperationsController::class, 'exportTelemetry'])->name('admin.transport.telemetry.export');
        Route::get('/telemetry', [TransportOperationsController::class, 'telemetry'])->name('admin.transport.telemetry.index');
        Route::get('/alerts/export', [TransportOperationsController::class, 'exportAlerts'])->name('admin.transport.alerts.export');
        Route::get('/alerts', [TransportOperationsController::class, 'alerts'])->name('admin.transport.alerts.index');
        Route::get('/alerts/{alert}', [TransportOperationsController::class, 'alert'])->name('admin.transport.alerts.show');
        Route::get('/sync-health', [TransportOperationsController::class, 'sync'])->name('admin.transport.sync.index');
    });
    Route::prefix('processor')->group(function (): void {
        Route::get('/facilities', [ProcessorOperationsController::class, 'facilities'])->name('admin.processor.facilities.index');
        Route::get('/facilities/{profile}', [ProcessorOperationsController::class, 'facility'])->name('admin.processor.facilities.show');
        Route::get('/intakes', [ProcessorOperationsController::class, 'intakes'])->name('admin.processor.intakes.index');
        Route::get('/intakes/{intake}', [ProcessorOperationsController::class, 'intake'])->name('admin.processor.intakes.show');
        Route::get('/records/export', [ProcessorOperationsController::class, 'exportRecords'])->name('admin.processor.records.export');
        Route::get('/records', [ProcessorOperationsController::class, 'records'])->name('admin.processor.records.index');
        Route::get('/records/{record}', [ProcessorOperationsController::class, 'record'])->name('admin.processor.records.show');
        Route::get('/inspections/export', [ProcessorOperationsController::class, 'exportInspections'])->name('admin.processor.inspections.export');
        Route::get('/inspections', [ProcessorOperationsController::class, 'inspections'])->name('admin.processor.inspections.index');
        Route::get('/inspections/{inspection}', [ProcessorOperationsController::class, 'inspection'])->name('admin.processor.inspections.show');
        Route::get('/labels', [ProcessorOperationsController::class, 'labels'])->name('admin.processor.labels.index');
        Route::get('/labels/{label}', [ProcessorOperationsController::class, 'label'])->name('admin.processor.labels.show');
    });
    Route::prefix('retail')->group(function (): void {
        Route::get('/retailers', [RetailOperationsController::class, 'retailers'])->name('admin.retail.retailers.index');
        Route::get('/retailers/{retailer}', [RetailOperationsController::class, 'retailer'])->name('admin.retail.retailers.show');
        Route::get('/locations', [RetailOperationsController::class, 'locations'])->name('admin.retail.locations.index');
        Route::get('/locations/{location}', [RetailOperationsController::class, 'location'])->name('admin.retail.locations.show');
        Route::get('/receipts', [RetailOperationsController::class, 'receipts'])->name('admin.retail.receipts.index');
        Route::get('/receipts/{receipt}', [RetailOperationsController::class, 'receipt'])->name('admin.retail.receipts.show');
        Route::get('/inventory/export', [RetailOperationsController::class, 'exportInventory'])->name('admin.retail.inventory.export');
        Route::get('/inventory', [RetailOperationsController::class, 'inventory'])->name('admin.retail.inventory.index');
        Route::get('/inventory/{lot}', [RetailOperationsController::class, 'lot'])->name('admin.retail.inventory.show');
        Route::get('/movements', [RetailOperationsController::class, 'movements'])->name('admin.retail.movements.index');
        Route::get('/sales/export', [RetailOperationsController::class, 'exportSales'])->name('admin.retail.sales.export');
        Route::get('/sales', [RetailOperationsController::class, 'sales'])->name('admin.retail.sales.index');
        Route::get('/sales/{sale}', [RetailOperationsController::class, 'sale'])->name('admin.retail.sales.show');
        Route::get('/risks', [RetailOperationsController::class, 'risks'])->name('admin.retail.risks.index');
    });
    Route::prefix('compliance')->group(function (): void {
        Route::get('/incidents/export', [ComplianceOperationsController::class, 'exportIncidents'])->name('admin.compliance.incidents.export');
        Route::get('/incidents', [ComplianceOperationsController::class, 'incidents'])->name('admin.compliance.incidents.index');
        Route::get('/incidents/{inspection}', [ComplianceOperationsController::class, 'incident'])->name('admin.compliance.incidents.show');
        Route::get('/recalls/export', [ComplianceOperationsController::class, 'exportRecalls'])->name('admin.compliance.recalls.export');
        Route::get('/recalls', [ComplianceOperationsController::class, 'recalls'])->name('admin.compliance.recalls.index');
        Route::get('/evidence', [ComplianceOperationsController::class, 'evidence'])->name('admin.compliance.evidence.index');
        Route::get('/evidence/{file}/download', [ComplianceOperationsController::class, 'download'])->name('admin.compliance.evidence.download');
        Route::get('/notifications', [ComplianceOperationsController::class, 'notifications'])->name('admin.compliance.notifications.index');
        Route::get('/reports', [ComplianceOperationsController::class, 'reports'])->name('admin.compliance.reports.index');
        Route::get('/ai', [ComplianceOperationsController::class, 'ai'])->name('admin.compliance.ai.index');
        Route::get('/blockchain', [ComplianceOperationsController::class, 'blockchain'])->name('admin.compliance.blockchain.index');
        Route::get('/blockchain/{transaction}', [ComplianceOperationsController::class, 'transaction'])->name('admin.compliance.blockchain.show');
    });
    Route::get('/users', [UserController::class, 'index'])->name('admin.users.index');
    Route::get('/users/create', [UserController::class, 'create'])->name('admin.users.create');
    Route::post('/users', [UserController::class, 'store'])->name('admin.users.store');
    Route::get('/users/{managedUser}', [UserController::class, 'show'])->name('admin.users.show');
    Route::get('/users/{managedUser}/edit', [UserController::class, 'edit'])->name('admin.users.edit');
    Route::put('/users/{managedUser}', [UserController::class, 'update'])->name('admin.users.update');
    Route::post('/users/{managedUser}/activate', [UserController::class, 'activate'])->name('admin.users.activate');
    Route::post('/users/{managedUser}/deactivate', [UserController::class, 'deactivate'])->name('admin.users.deactivate');
    Route::post('/users/{managedUser}/unlock', [UserController::class, 'unlock'])->name('admin.users.unlock');
    Route::post('/users/{managedUser}/revoke-sessions', [UserController::class, 'revokeSessions'])->name('admin.users.revoke-sessions');
    Route::post('/users/{managedUser}/reset-password', [UserController::class, 'resetPassword'])->name('admin.users.reset-password');
    Route::get('/organizations', [OrganizationController::class, 'index'])->name('admin.organizations.index');
    Route::get('/organizations/create', [OrganizationController::class, 'create'])->name('admin.organizations.create');
    Route::post('/organizations', [OrganizationController::class, 'store'])->name('admin.organizations.store');
    Route::get('/organizations/{organization}', [OrganizationController::class, 'show'])->name('admin.organizations.show');
    Route::get('/organizations/{organization}/edit', [OrganizationController::class, 'edit'])->name('admin.organizations.edit');
    Route::put('/organizations/{organization}', [OrganizationController::class, 'update'])->name('admin.organizations.update');
    Route::post('/organizations/{organization}/activate', [OrganizationController::class, 'activate'])->name('admin.organizations.activate');
    Route::post('/organizations/{organization}/deactivate', [OrganizationController::class, 'deactivate'])->name('admin.organizations.deactivate');
    Route::get('/roles', RoleController::class)->name('admin.roles.index');
    Route::get('/settings/alert-rules', [AlertRuleController::class, 'index'])->name('admin.settings.alert-rules.index');
    Route::put('/settings/alert-rules', [AlertRuleController::class, 'update'])->name('admin.settings.alert-rules.update');
    Route::get('/settings/system', [SystemSettingController::class, 'edit'])->name('admin.settings.system.edit');
    Route::put('/settings/system', [SystemSettingController::class, 'update'])->name('admin.settings.system.update');
    Route::get('/profile', [AdminProfileController::class, 'edit'])->name('admin.settings.profile.edit');
    Route::put('/profile', [AdminProfileController::class, 'update'])->name('admin.settings.profile.update');
    Route::get('/security', [AdminProfileController::class, 'security'])->name('admin.settings.security.index');
    Route::put('/security/password', [AdminProfileController::class, 'password'])->name('admin.settings.security.password');
    Route::post('/security/revoke-other-sessions', [AdminProfileController::class, 'revokeOtherSessions'])->name('admin.settings.security.revoke-other-sessions');
    Route::post('/logout', [AdminAuthController::class, 'destroy'])->name('admin.logout');
});
