<x-layouts.admin title="Security settings | FishTrace">
    <header><p class="text-sm font-medium text-cyan-700">Account</p><h1 class="text-3xl font-bold">Security settings</h1><p class="mt-1 text-slate-500">Change your password and review or revoke authenticated sessions.</p></header>
    @include('admin.settings._nav')
    <div class="mt-6 grid gap-6 xl:grid-cols-2">
        <form method="post" action="{{ route('admin.settings.security.password') }}" class="rounded-xl bg-white p-6 shadow-sm">@csrf @method('PUT')<h2 class="text-lg font-bold">Change password</h2><p class="mt-1 text-sm text-slate-500">Changing it revokes every API token and all browser sessions except this one.</p><div class="mt-5 space-y-4"><label class="block"><span class="text-sm font-medium">Current password</span><input type="password" name="current_password" required autocomplete="current-password" class="mt-1 w-full rounded-lg border-slate-300"></label><label class="block"><span class="text-sm font-medium">New password</span><input type="password" name="password" required autocomplete="new-password" class="mt-1 w-full rounded-lg border-slate-300"></label><label class="block"><span class="text-sm font-medium">Confirm new password</span><input type="password" name="password_confirmation" required autocomplete="new-password" class="mt-1 w-full rounded-lg border-slate-300"></label></div><button class="mt-6 rounded-lg bg-[#075e63] px-5 py-2.5 font-semibold text-white">Change password</button></form>
        <section class="rounded-xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Session controls</h2><p class="mt-1 text-sm text-slate-500">API tokens: {{ $api_token_count }}. Up to 20 recent browser sessions are shown.</p><form method="post" action="{{ route('admin.settings.security.revoke-other-sessions') }}" class="mt-5">@csrf<label class="block"><span class="text-sm font-medium">Current password</span><input type="password" name="current_password" required autocomplete="current-password" class="mt-1 w-full rounded-lg border-slate-300"></label><button class="mt-4 rounded-lg border border-red-300 px-4 py-2 font-semibold text-red-700">Revoke other sessions and API tokens</button></form></section>
    </div>
    <section class="mt-6 overflow-hidden rounded-xl bg-white shadow-sm" aria-labelledby="session-list"><header class="border-b p-5"><h2 id="session-list" class="font-bold">Recent browser sessions</h2></header><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">Status</th><th>IP address</th><th>Browser</th><th>Last activity</th></tr></thead><tbody>@forelse($sessions as $session)<tr class="border-t"><td class="p-4"><x-admin.status :value="$session['is_current'] ? 'CURRENT' : 'OTHER'" /></td><td>{{ $session['ip_address'] ?? 'Unknown' }}</td><td class="max-w-md truncate" title="{{ $session['user_agent'] }}">{{ $session['user_agent'] ?? 'Unknown' }}</td><td>{{ \Carbon\Carbon::createFromTimestamp($session['last_activity'])->format('Y-m-d H:i:s') }}</td></tr>@empty<tr><td colspan="4" class="p-10 text-center text-slate-500">No database-backed browser sessions are currently recorded.</td></tr>@endforelse</tbody></table></section>
</x-layouts.admin>
