<x-layouts.admin title="Fishers | FishTrace">
    @include('admin.fishing._nav')
    <header><p class="text-sm font-medium text-cyan-700">Fishing operations</p><h1 class="text-3xl font-bold">Fishers</h1><p class="mt-1 text-slate-500">Operational profiles derived from identities, memberships, vessels, trips, and catches.</p></header>
    <form class="mt-6 grid gap-3 rounded-xl bg-white p-4 shadow-sm md:grid-cols-4">
        <input name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Name or email" class="rounded-lg border-slate-300">
        <select name="organization_id" class="rounded-lg border-slate-300"><option value="">All cooperatives</option>@foreach ($organizations as $organization)<option value="{{ $organization->id }}" @selected(($filters['organization_id'] ?? '') === $organization->id)>{{ $organization->name }}</option>@endforeach</select>
        <select name="status" class="rounded-lg border-slate-300"><option value="">All statuses</option><option value="ACTIVE" @selected(($filters['status'] ?? '') === 'ACTIVE')>Active</option><option value="DISABLED" @selected(($filters['status'] ?? '') === 'DISABLED')>Disabled</option></select>
        <div class="flex gap-2"><button class="flex-1 rounded-lg bg-slate-800 px-4 py-2 text-white">Filter</button><a href="{{ route('admin.fishing.fishers.index') }}" class="rounded-lg border border-slate-300 px-4 py-2">Clear</a></div>
    </form>
    <section class="mt-6 overflow-hidden rounded-xl bg-white shadow-sm"><table class="w-full text-left text-sm"><thead class="border-b bg-slate-50 text-slate-500"><tr><th class="p-4">Fisher</th><th>Organization</th><th>Boats</th><th>Trips</th><th>Status</th></tr></thead><tbody>@forelse ($fishers as $fisher)<tr class="border-b border-slate-100"><td class="p-4"><a href="{{ route('admin.fishing.fishers.show', $fisher) }}" class="font-semibold text-cyan-700">{{ $fisher->name }}</a><div class="text-slate-500">{{ $fisher->email }}</div></td><td>{{ $fisher->organizations->first()?->name ?? '—' }}</td><td>{{ $fisher->owned_boats_count }}</td><td>{{ $fisher->fishing_trips_count }}</td><td>{{ $fisher->isLocked() ? 'LOCKED' : $fisher->status }}</td></tr>@empty<tr><td colspan="5" class="p-10 text-center text-slate-500">No fishers match these filters.</td></tr>@endforelse</tbody></table><div class="p-4">{{ $fishers->links() }}</div></section>
</x-layouts.admin>
