<?php

namespace App\Enums;

enum BatchStatus: string
{
    case CREATED = 'CREATED';
    case AVAILABLE_FOR_PROCESSING = 'AVAILABLE_FOR_PROCESSING';
    case ACCEPTED_BY_PROCESSOR = 'ACCEPTED_BY_PROCESSOR';
    case PROCESSING = 'PROCESSING';
    case PROCESSED = 'PROCESSED';
    case READY_FOR_TRANSPORT = 'READY_FOR_TRANSPORT';
    case IN_TRANSPORT = 'IN_TRANSPORT';
    case RECEIVED_BY_RETAILER = 'RECEIVED_BY_RETAILER';
    case AVAILABLE_FOR_SALE = 'AVAILABLE_FOR_SALE';
    case SOLD = 'SOLD';
    case RECALLED = 'RECALLED';
}
