<?php

namespace App\Enums;

enum NotificationType: string
{
    case HIGH_TEMPERATURE = 'HIGH_TEMPERATURE';
    case CRITICAL_TEMPERATURE = 'CRITICAL_TEMPERATURE';
    case DEVICE_OFFLINE = 'DEVICE_OFFLINE';
    case LOW_BATTERY = 'LOW_BATTERY';
    case BATCH_ACCEPTED = 'BATCH_ACCEPTED';
    case BATCH_REJECTED = 'BATCH_REJECTED';
    case PROCESSING_COMPLETED = 'PROCESSING_COMPLETED';
    case INSPECTION_FAILED = 'INSPECTION_FAILED';
    case TRANSPORT_STARTED = 'TRANSPORT_STARTED';
    case DELIVERY_COMPLETED = 'DELIVERY_COMPLETED';
    case RETAIL_RECEIPT = 'RETAIL_RECEIPT';
    case RECALL = 'RECALL';
    case HIGH_AI_RISK = 'HIGH_AI_RISK';
    case AI_SERVICE_FAILURE = 'AI_SERVICE_FAILURE';
    case BLOCKCHAIN_SUBMISSION_FAILURE = 'BLOCKCHAIN_SUBMISSION_FAILURE';
    case BLOCKCHAIN_VERIFICATION_FAILURE = 'BLOCKCHAIN_VERIFICATION_FAILURE';
    case FIREBASE_ASSIGNMENT_FAILURE = 'FIREBASE_ASSIGNMENT_FAILURE';
    case FIREBASE_IMPORT_FAILURE = 'FIREBASE_IMPORT_FAILURE';
    case REPORT_EXPORT_READY = 'REPORT_EXPORT_READY';
    case REPORT_EXPORT_FAILED = 'REPORT_EXPORT_FAILED';
    case ROUTE_DEVIATION = 'ROUTE_DEVIATION';
    case DESTINATION_GEOFENCE = 'DESTINATION_GEOFENCE';
}
